# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            DeepAnalysisResearch
tagline:          'Home for DAR'
description:      'A site for Research and Blog shared from team'
url:              https://snowaner-ustc.github.io/
baseurl:          https://snowaner-ustc.github.io/

author:
  name:           'DeepAnalysisResearch'
  url:            

paginate:         2
paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://snowaner-ustc.github.io/
